# Generated by Django 5.0.3 on 2024-05-09 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_item_resident_delete_message_delete_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='name',
            new_name='description',
        ),
        migrations.AddField(
            model_name='item',
            name='resident_id',
            field=models.IntegerField(default=0),
        ),
    ]
