# Generated by Django 5.0.3 on 2024-05-09 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_rename_name_item_description_item_resident_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='description',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='item',
            name='resident_id',
        ),
    ]
