# Generated by Django 5.0.3 on 2024-05-29 01:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='date_of_admittance',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
