# Generated by Django 5.0.3 on 2024-05-29 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_resident_date_of_admittance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resident',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='resident',
            name='last_name',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
